[project]
name = "web3test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "eth-account>=0.13.7",
    "ipykernel>=6.30.0",
    "py-solc-x>=2.0.4",
    "python-dotenv>=1.1.1",
    "web3>=7.12.1",
]
